/**
 * Base icons for navigation, status, actions, devices, OS, and general UI.
 * These are manually mapped to specific SVG files in the assets directory.
 */
export const BASE_ICONS: Record<string, string> = {
  // ------------------- Navigation Icons -------------------
  'circle-chevron-down': 'assets/icons/navigation/circle-chevron-down.svg',
  'circle-chevron-up': 'assets/icons/navigation/circle-chevron-up.svg',
  'arrow-turn-up-left': 'assets/icons/navigation/arrow-turn-up-left.svg',
  'chevron-up': 'assets/icons/navigation/chevron-up.svg',
  'chevron-down': 'assets/icons/navigation/chevron-down.svg',
  'caret-down': 'assets/icons/navigation/caret-down.svg',
  'caret-up': 'assets/icons/navigation/caret-up.svg',
  'chevron-left': 'assets/icons/navigation/chevron-left.svg',
  'chevron-right': 'assets/icons/navigation/chevron-right.svg',
  'left-arrow': 'assets/icons/navigation/circle-arrow-left.svg',
  'no-internet': 'assets/icons/navigation/no-internet.svg',
  'open-link': 'assets/icons/navigation/arrow-up-right-from-square.svg',
  'right-arrow': 'assets/icons/navigation/circle-arrow-right.svg',
  'arrow-down': 'assets/icons/navigation/circle-arrow-down.svg',
  'right-left': 'assets/icons/navigation/right-left.svg',

  // ------------------- Status Icons -------------------
  'circle-check': 'assets/icons/status/circle-check.svg',
  'circle-exclamation': 'assets/icons/status/circle-exclamation.svg',
  'circle-info': 'assets/icons/status/circle-info.svg',
  'circle-up': 'assets/icons/status/circle-up.svg',
  'circle-xmark': 'assets/icons/status/circle-xmark.svg',
  warning: 'assets/icons/status/warning.svg',
  error: 'assets/icons/status/circle-exclamation.svg',
  lock: 'assets/icons/status/lock.svg',
  'lock-open': 'assets/icons/status/lock-open.svg',
  shield: 'assets/icons/status/shield.svg',
  security: 'assets/icons/status/security.svg',
  key: 'assets/icons/status/key.svg',
  fingerprint: 'assets/icons/status/fingerprint.svg',
  star: 'assets/icons/status/star.svg',
  'star-outline': 'assets/icons/status/star-outline.svg',
  question: 'assets/icons/status/question.svg',

  // ------------------- File & Folder Icons -------------------
  file: 'assets/icons/files/file.svg',
  folder: 'assets/icons/files/folder.svg',
  'file-zipper': 'assets/icons/files/file-zipper.svg',
  'file-lines': 'assets/icons/files/file-lines.svg',
  'file-arrow-up': 'assets/icons/files/file-arrow-up.svg',
  database: 'assets/icons/files/database.svg',
  package: 'assets/icons/files/package.svg',
  'box-archive': 'assets/icons/files/box-archive.svg',
  'note-sticky': 'assets/icons/files/note-sticky.svg',

  // ------------------- Action Icons -------------------
  plus: 'assets/icons/titlebar/add.svg',
  new: 'assets/icons/titlebar/add.svg',
  remove: 'assets/icons/actions/remove.svg',
  close: 'assets/icons/titlebar/close.svg',
  copy: 'assets/icons/actions/copy.svg',
  move: 'assets/icons/actions/move.svg',
  download: 'assets/icons/actions/download.svg',
  'cloud-arrow-up': 'assets/icons/actions/cloud-arrow-up.svg',
  export: 'assets/icons/actions/export.svg',
  eject: 'assets/icons/actions/eject.svg',
  pen: 'assets/icons/actions/pen.svg',
  trash: 'assets/icons/actions/trash.svg',
  filter: 'assets/icons/actions/filter.svg',
  search: 'assets/icons/titlebar/search.svg',
  refresh: 'assets/icons/actions/rotate.svg',
  'rotate-right': 'assets/icons/actions/rotate-right.svg',
  'reset-wrench': 'assets/icons/actions/reset-wrench.svg',
  sync: 'assets/icons/files/folder-sync.svg',
  play: 'assets/icons/actions/play.svg',
  pause: 'assets/icons/actions/pause.svg',
  stop: 'assets/icons/actions/stop.svg',
  eye: 'assets/icons/actions/eye.svg',
  'eye-slash': 'assets/icons/actions/eye-slash.svg',
  'power-off': 'assets/icons/actions/power-off.svg',
  broom: 'assets/icons/actions/broom.svg',
  'floppy-disk': 'assets/icons/actions/floppy-disk.svg',

  // ------------------- Device Icons -------------------
  'hard-drive': 'assets/icons/devices/hard-drive.svg',
  server: 'assets/icons/devices/server.svg',
  cloud: 'assets/icons/devices/cloud.svg',
  tv: 'assets/icons/devices/tv.svg',
  'satellite-dish': 'assets/icons/devices/satellite-dish.svg',
  serve: 'assets/icons/devices/satellite-dish.svg',
  globe: 'assets/icons/devices/globe.svg',
  bolt: 'assets/icons/devices/bolt.svg',

  // ------------------- OS Icons -------------------
  apple: 'assets/icons/os/apple.svg',
  linux: 'assets/icons/os/linux.svg',
  windows: 'assets/icons/os/windows.svg',

  // ------------------- General Icons -------------------
  home: 'assets/icons/general/home.svg',
  gear: 'assets/icons/general/gear.svg',
  info: 'assets/icons/general/info.svg',
  bug: 'assets/icons/general/bug.svg',
  chart: 'assets/icons/general/chart.svg',
  flask: 'assets/icons/general/flask.svg',
  jobs: 'assets/icons/general/jobs.svg',
  terminal: 'assets/icons/general/terminal.svg',
  wrench: 'assets/icons/general/wrench.svg',
  list: 'assets/icons/general/list.svg',
  grid: 'assets/icons/general/grid.svg',
  comment: 'assets/icons/general/comment.svg',
  tag: 'assets/icons/general/tag.svg',
  bucket: 'assets/icons/general/bucket.svg',
  skull: 'assets/icons/general/skull.svg',
  'puzzle-piece': 'assets/icons/general/puzzle-piece.svg',
  wind: 'assets/icons/general/wind.svg',
  bookmark: 'assets/icons/general/bookmark.svg',
  calendar: 'assets/icons/general/calendar.svg',
  clock: 'assets/icons/general/clock.svg',
  'clock-rotate-right': 'assets/icons/general/clock-rotate-right.svg',
  vfs: 'assets/icons/general/vfs.svg',
  mount: 'assets/icons/general/mount.svg',
  user: 'assets/icons/general/user.svg',
  code: 'assets/icons/general/code.svg',
  scissors: 'assets/icons/general/scissors.svg',

  // ------------------- Titlebar Icons -------------------
  expand: 'assets/icons/titlebar/expand.svg',
  collapse: 'assets/icons/titlebar/collapse.svg',
  minimize: 'assets/icons/titlebar/minimize.svg',
  'ellipsis-vertical': 'assets/icons/titlebar/ellipsis-vertical.svg',
  'menu-bar': 'assets/icons/titlebar/menu-bar.svg',

  // ------------------- Remote Icons -------------------
  drive: 'assets/icons/remotes/drive.svg',
  dropbox: 'assets/icons/remotes/dropbox.svg',
  ftp: 'assets/icons/remotes/ftp.svg',
  memory: 'assets/icons/remotes/memory.svg',
  onedrive: 'assets/icons/remotes/onedrive.svg',
  s3: 'assets/icons/remotes/s3.svg',
  mega: 'assets/icons/remotes/mega.svg',
  protondrive: 'assets/icons/remotes/protondrive.svg',
  iclouddrive: 'assets/icons/remotes/iclouddrive.svg',
  http: 'assets/icons/devices/globe.svg',
  webdav: 'assets/icons/remotes/webdav.svg',
  sftp: 'assets/icons/remotes/sftp.svg',
  hdfs: 'assets/icons/remotes/hdfs.svg',
  box: 'assets/icons/remotes/box.svg',
  yandex: 'assets/icons/remotes/yandex.svg',
  'google photos': 'assets/icons/remotes/google.svg',
  'google cloud storage': 'assets/icons/remotes/google.svg',
  jottacloud: 'assets/icons/remotes/jottacloud.svg',
  hidrive: 'assets/icons/remotes/hidrive.svg',
  pcloud: 'assets/icons/remotes/pcloud.svg',
  storj: 'assets/icons/remotes/storj.svg',
  internetarchive: 'assets/icons/remotes/internetarchive.svg',
  azureblob: 'assets/icons/remotes/azure.svg',
  azurefiles: 'assets/icons/remotes/azure.svg',
  rclone: 'assets/rclone-symbolic.svg',
  aws: 'assets/icons/remotes/s3.svg',
};
