/**
 * Mapping of file extensions to their corresponding Adwaita icon names.
 * This is often the most reliable way to determine an icon when MIME types are generic.
 */
export const MIME_EXTENSION_MAP: Record<string, string> = {
  // --- Archives ---
  '7z': 'package-x-generic',
  apk: 'android-package-archive',
  ar: 'package-x-generic',
  bz2: 'package-x-generic',
  cab: 'package-x-generic',
  cpio: 'package-x-generic',
  deb: 'application-x-deb',
  dmg: 'package-x-generic',
  gz: 'package-x-generic',
  iso: 'application-x-cd-image',
  jar: 'application-x-java-archive',
  rar: 'package-x-generic',
  rpm: 'application-x-rpm',
  tar: 'package-x-generic',
  tgz: 'package-x-generic',
  zip: 'package-x-generic',
  xz: 'package-x-generic',
  z: 'package-x-generic',

  // --- Code & Scripts ---
  c: 'text-x-c',
  cc: 'text-x-cpp',
  cpp: 'text-x-cpp',
  cs: 'text-x-csharp',
  css: 'text-css',
  go: 'text-x-go',
  h: 'text-x-chdr',
  hpp: 'text-x-cpphdr',
  html: 'application-xml',
  htm: 'application-xml',
  java: 'text-x-java',
  js: 'text-x-javascript',
  json: 'application-json',
  jsx: 'text-x-javascript',
  kt: 'text-x-kotlin',
  lua: 'text-x-lua',
  md: 'text-x-markdown',
  mk: 'text-x-makefile',
  php: 'application-x-php',
  pl: 'application-x-perl',
  py: 'text-x-python',
  rb: 'text-x-ruby',
  rs: 'text-rust',
  sass: 'text-css',
  scss: 'text-css',
  sh: 'application-x-shellscript',
  sql: 'text-x-generic',
  ts: 'text-x-typescript',
  tsx: 'text-x-typescript',
  xml: 'application-xml',
  yaml: 'application-x-yaml',
  yml: 'application-x-yaml',
  vue: 'text-x-generic',

  // --- Documents ---
  doc: 'x-office-document',
  docx: 'x-office-document',
  odp: 'oasis-presentation',
  ods: 'oasis-spreadsheet',
  odt: 'oasis-text',
  pdf: 'application-pdf',
  ppt: 'oasis-presentation',
  pptx: 'oasis-presentation',
  rtf: 'text-x-generic',
  xls: 'oasis-spreadsheet',
  xlsx: 'oasis-spreadsheet',
  csv: 'text-x-generic',
  txt: 'text-x-generic',

  // --- Media - Audio ---
  aac: 'audio-x-generic',
  flac: 'audio-x-generic',
  m4a: 'audio-x-generic',
  mp3: 'audio-x-generic',
  ogg: 'audio-x-generic',
  wav: 'audio-x-generic',

  // --- Media - Images ---
  bmp: 'image-x-generic',
  gif: 'image-x-generic',
  ico: 'image-x-generic',
  jpeg: 'image-x-generic',
  jpg: 'image-x-generic',
  png: 'image-x-generic',
  svg: 'image-x-generic',
  tif: 'image-x-generic',
  tiff: 'image-x-generic',
  webp: 'image-x-generic',
  xcf: 'image-x-generic',
  kra: 'image-x-generic',
  psd: 'application-x-photoshop',

  // --- Media - Video ---
  avi: 'video-x-generic',
  flv: 'video-x-generic',
  mkv: 'video-x-generic',
  mov: 'video-x-generic',
  mp4: 'video-x-generic',
  mpeg: 'video-x-generic',
  mpg: 'video-x-generic',
  webm: 'video-x-generic',
  wmv: 'video-x-generic',

  // --- Database & Other ---
  db: 'text-x-generic',
  sqlite: 'text-x-generic',
  sqlite3: 'text-x-generic',
  torrent: 'application-x-bittorrent',
  vbox: 'virtualbox-vbox',
  vdi: 'virtualbox-vdi',
};
