export const ADWAITA_ICONS: Record<string, string> = {
  'android-package-archive': 'assets/icons/adwaita/mimetypes/android-package-archive.svg',
  'application-affinity': 'assets/icons/adwaita/mimetypes/application-affinity.svg',
  'application-affinity-template':
    'assets/icons/adwaita/mimetypes/application-affinity-template.svg',
  'application-epub+zip': 'assets/icons/adwaita/mimetypes/application-epub+zip.svg',
  'application-illustrator': 'assets/icons/adwaita/mimetypes/application-illustrator.svg',
  'application-json': 'assets/icons/adwaita/mimetypes/application-json.svg',
  'application-loc+xml': 'assets/icons/adwaita/mimetypes/application-loc+xml.svg',
  'application-mathematicaplayer':
    'assets/icons/adwaita/mimetypes/application-mathematicaplayer.svg',
  'application-mathematica': 'assets/icons/adwaita/mimetypes/application-mathematica.svg',
  'application-mbox': 'assets/icons/adwaita/mimetypes/application-mbox.svg',
  'application-octet-stream': 'assets/icons/adwaita/mimetypes/application-octet-stream.svg',
  'application-pdf': 'assets/icons/adwaita/mimetypes/application-pdf.svg',
  'application-pgp-encrypted': 'assets/icons/adwaita/mimetypes/application-pgp-encrypted.svg',
  'application-pgp-keys': 'assets/icons/adwaita/mimetypes/application-pgp-keys.svg',
  'application-pgp-signature': 'assets/icons/adwaita/mimetypes/application-pgp-signature.svg',
  'application-pkix-cert': 'assets/icons/adwaita/mimetypes/application-pkix-cert.svg',
  'application-postscript': 'assets/icons/adwaita/mimetypes/application-postscript.svg',
  'application-toml': 'assets/icons/adwaita/mimetypes/application-toml.svg',
  'application-vnd.adobe.aftereffects.project':
    'assets/icons/adwaita/mimetypes/application-vnd.adobe.aftereffects.project.svg',
  'application-vnd.adobe.xd': 'assets/icons/adwaita/mimetypes/application-vnd.adobe.xd.svg',
  'application-vnd.comicbook+zip':
    'assets/icons/adwaita/mimetypes/application-vnd.comicbook+zip.svg',
  'application-vnd.flatpak': 'assets/icons/adwaita/mimetypes/application-vnd.flatpak.svg',
  'application-vnd.iccprofile': 'assets/icons/adwaita/mimetypes/application-vnd.iccprofile.svg',
  'application-vnd.leocad': 'assets/icons/adwaita/mimetypes/application-vnd.leocad.svg',
  'application-vnd.scribus': 'assets/icons/adwaita/mimetypes/application-vnd.scribus.svg',
  'application-vnd.snap': 'assets/icons/adwaita/mimetypes/application-vnd.snap.svg',
  'application-vnd.wolfram.mathematica.package':
    'assets/icons/adwaita/mimetypes/application-vnd.wolfram.mathematica.package.svg',
  'application-wasm': 'assets/icons/adwaita/mimetypes/application-wasm.svg',
  'application-x-adobe-indesign': 'assets/icons/adwaita/mimetypes/application-x-adobe-indesign.svg',
  'application-x-audacity-project':
    'assets/icons/adwaita/mimetypes/application-x-audacity-project.svg',
  'application-x-bittorrent': 'assets/icons/adwaita/mimetypes/application-x-bittorrent.svg',
  'application-x-bitwig-studio': 'assets/icons/adwaita/mimetypes/application-x-bitwig-studio.svg',
  'application-x-cd-image': 'assets/icons/adwaita/mimetypes/application-x-cd-image.svg',
  'application-x-cson': 'assets/icons/adwaita/mimetypes/application-x-cson.svg',
  'application-x-deb': 'assets/icons/adwaita/mimetypes/application-x-deb.svg',
  'application-x-designer': 'assets/icons/adwaita/mimetypes/application-x-designer.svg',
  'application-x-firmware': 'assets/icons/adwaita/mimetypes/application-x-firmware.svg',
  'application-x-gettext-translation':
    'assets/icons/adwaita/mimetypes/application-x-gettext-translation.svg',
  'application-x-godot-project': 'assets/icons/adwaita/mimetypes/application-x-godot-project.svg',
  'application-x-hwp': 'assets/icons/adwaita/mimetypes/application-x-hwp.svg',
  'application-x-ipynb+json': 'assets/icons/adwaita/mimetypes/application-x-ipynb+json.svg',
  'application-x-iso9600-appimage':
    'assets/icons/adwaita/mimetypes/application-x-iso9600-appimage.svg',
  'application-x-java-archive': 'assets/icons/adwaita/mimetypes/application-x-java-archive.svg',
  'application-x-kdenlive': 'assets/icons/adwaita/mimetypes/application-x-kdenlive.svg',
  'application-xml': 'assets/icons/adwaita/mimetypes/application-xml.svg',
  'application-x-model': 'assets/icons/adwaita/mimetypes/application-x-model.svg',
  'application-x-musescore4portable':
    'assets/icons/adwaita/mimetypes/application-x-musescore4portable.svg',
  'application-x-musescore4portable+xml':
    'assets/icons/adwaita/mimetypes/application-x-musescore4portable+xml.svg',
  'application-x-perl': 'assets/icons/adwaita/mimetypes/application-x-perl.svg',
  'application-x-photoshop': 'assets/icons/adwaita/mimetypes/application-x-photoshop.svg',
  'application-x-php': 'assets/icons/adwaita/mimetypes/application-x-php.svg',
  'application-x-python-bytecode':
    'assets/icons/adwaita/mimetypes/application-x-python-bytecode.svg',
  'application-x-rpm': 'assets/icons/adwaita/mimetypes/application-x-rpm.svg',
  'application-x-shellscript': 'assets/icons/adwaita/mimetypes/application-x-shellscript.svg',
  'application-x-spectrum': 'assets/icons/adwaita/mimetypes/application-x-spectrum.svg',
  'application-x-subrip': 'assets/icons/adwaita/mimetypes/application-x-subrip.svg',
  'application-x-theme': 'assets/icons/adwaita/mimetypes/application-x-theme.svg',
  'application-x-xopp': 'assets/icons/adwaita/mimetypes/application-x-xopp.svg',
  'application-x-yaml': 'assets/icons/adwaita/mimetypes/application-x-yaml.svg',
  'audio-x-generic': 'assets/icons/adwaita/mimetypes/audio-x-generic.svg',
  'cockos-reaper-backup': 'assets/icons/adwaita/mimetypes/cockos-reaper-backup.svg',
  'cockos-reaper-document': 'assets/icons/adwaita/mimetypes/cockos-reaper-document.svg',
  'cockos-reaper-peak': 'assets/icons/adwaita/mimetypes/cockos-reaper-peak.svg',
  'cockos-reaper-template2': 'assets/icons/adwaita/mimetypes/cockos-reaper-template2.svg',
  'cockos-reaper-template': 'assets/icons/adwaita/mimetypes/cockos-reaper-template.svg',
  'cockos-reaper-theme': 'assets/icons/adwaita/mimetypes/cockos-reaper-theme.svg',
  'com.bitwig.BitwigStudio.audio-x.dawproject':
    'assets/icons/adwaita/mimetypes/com.bitwig.BitwigStudio.audio-x.dawproject.svg',
  'com.fender.studio.application-x.fender-fenderstudio':
    'assets/icons/adwaita/mimetypes/com.fender.studio.application-x.fender-fenderstudio.svg',
  'com.fender.studio.application-x.fender-jamtrack':
    'assets/icons/adwaita/mimetypes/com.fender.studio.application-x.fender-jamtrack.svg',
  'font-x-generic': 'assets/icons/adwaita/mimetypes/font-x-generic.svg',
  'image-vnd.djvu': 'assets/icons/adwaita/mimetypes/image-vnd.djvu.svg',
  'image-x-generic': 'assets/icons/adwaita/mimetypes/image-x-generic.svg',
  'oasis-database': 'assets/icons/adwaita/mimetypes/oasis-database.svg',
  'oasis-database-template': 'assets/icons/adwaita/mimetypes/oasis-database-template.svg',
  'oasis-drawing': 'assets/icons/adwaita/mimetypes/oasis-drawing.svg',
  'oasis-drawing-template': 'assets/icons/adwaita/mimetypes/oasis-drawing-template.svg',
  'oasis-empty': 'assets/icons/adwaita/mimetypes/oasis-empty.svg',
  'oasis-empty-template': 'assets/icons/adwaita/mimetypes/oasis-empty-template.svg',
  'oasis-formula': 'assets/icons/adwaita/mimetypes/oasis-formula.svg',
  'oasis-formula-template': 'assets/icons/adwaita/mimetypes/oasis-formula-template.svg',
  'oasis-master-document': 'assets/icons/adwaita/mimetypes/oasis-master-document.svg',
  'oasis-master-document-template':
    'assets/icons/adwaita/mimetypes/oasis-master-document-template.svg',
  'oasis-presentation': 'assets/icons/adwaita/mimetypes/oasis-presentation.svg',
  'oasis-presentation-template': 'assets/icons/adwaita/mimetypes/oasis-presentation-template.svg',
  'oasis-spreadsheet': 'assets/icons/adwaita/mimetypes/oasis-spreadsheet.svg',
  'oasis-spreadsheet-template': 'assets/icons/adwaita/mimetypes/oasis-spreadsheet-template.svg',
  'oasis-text': 'assets/icons/adwaita/mimetypes/oasis-text.svg',
  'oasis-text-template': 'assets/icons/adwaita/mimetypes/oasis-text-template.svg',
  'oasis-web': 'assets/icons/adwaita/mimetypes/oasis-web.svg',
  'oasis-web-template': 'assets/icons/adwaita/mimetypes/oasis-web-template.svg',
  'org.kiwix.desktop.x-zim_source':
    'assets/icons/adwaita/mimetypes/org.kiwix.desktop.x-zim_source.svg',
  'org.rncbc.qtractor.application-x-qtractor-archive':
    'assets/icons/adwaita/mimetypes/org.rncbc.qtractor.application-x-qtractor-archive.svg',
  'org.rncbc.qtractor.application-x-qtractor-session':
    'assets/icons/adwaita/mimetypes/org.rncbc.qtractor.application-x-qtractor-session.svg',
  'org.rncbc.qtractor.application-x-qtractor-template':
    'assets/icons/adwaita/mimetypes/org.rncbc.qtractor.application-x-qtractor-template.svg',
  'org.wireshark.Wireshark-mimetype':
    'assets/icons/adwaita/mimetypes/org.wireshark.Wireshark-mimetype.svg',
  'package-x-generic': 'assets/icons/adwaita/mimetypes/package-x-generic.svg',
  'text-asciidoc': 'assets/icons/adwaita/mimetypes/text-asciidoc.svg',
  'text-css': 'assets/icons/adwaita/mimetypes/text-css.svg',
  'text-pureDataPatch': 'assets/icons/adwaita/mimetypes/text-pureDataPatch.svg',
  'text-rust': 'assets/icons/adwaita/mimetypes/text-rust.svg',
  'text-x-arduino': 'assets/icons/adwaita/mimetypes/text-x-arduino.svg',
  'text-x-ass': 'assets/icons/adwaita/mimetypes/text-x-ass.svg',
  'text-x-bibtex': 'assets/icons/adwaita/mimetypes/text-x-bibtex.svg',
  'text-x-chdr': 'assets/icons/adwaita/mimetypes/text-x-chdr.svg',
  'text-x-clojure': 'assets/icons/adwaita/mimetypes/text-x-clojure.svg',
  'text-x-cobol': 'assets/icons/adwaita/mimetypes/text-x-cobol.svg',
  'text-x-coffeescript': 'assets/icons/adwaita/mimetypes/text-x-coffeescript.svg',
  'text-x-common-lisp': 'assets/icons/adwaita/mimetypes/text-x-common-lisp.svg',
  'text-x-cpphdr': 'assets/icons/adwaita/mimetypes/text-x-cpphdr.svg',
  'text-x-cpp': 'assets/icons/adwaita/mimetypes/text-x-cpp.svg',
  'text-x-csharp': 'assets/icons/adwaita/mimetypes/text-x-csharp.svg',
  'text-x-c': 'assets/icons/adwaita/mimetypes/text-x-c.svg',
  'text-x-emacs-lisp': 'assets/icons/adwaita/mimetypes/text-x-emacs-lisp.svg',
  'text-x-fsharp': 'assets/icons/adwaita/mimetypes/text-x-fsharp.svg',
  'text-x-generic': 'assets/icons/adwaita/mimetypes/text-x-generic.svg',
  'text-x-gettext-translation': 'assets/icons/adwaita/mimetypes/text-x-gettext-translation.svg',
  'text-x-gettext-translation-template':
    'assets/icons/adwaita/mimetypes/text-x-gettext-translation-template.svg',
  'text-x-go': 'assets/icons/adwaita/mimetypes/text-x-go.svg',
  'text-x-gradle-kotlin': 'assets/icons/adwaita/mimetypes/text-x-gradle-kotlin.svg',
  'text-x-gradle': 'assets/icons/adwaita/mimetypes/text-x-gradle.svg',
  'text-x-javascript': 'assets/icons/adwaita/mimetypes/text-x-javascript.svg',
  'text-x-java': 'assets/icons/adwaita/mimetypes/text-x-java.svg',
  'text-x-julia': 'assets/icons/adwaita/mimetypes/text-x-julia.svg',
  'text-x-kotlin': 'assets/icons/adwaita/mimetypes/text-x-kotlin.svg',
  'text-x-log': 'assets/icons/adwaita/mimetypes/text-x-log.svg',
  'text-x-lua': 'assets/icons/adwaita/mimetypes/text-x-lua.svg',
  'text-x-makefile': 'assets/icons/adwaita/mimetypes/text-x-makefile.svg',
  'text-x-markdown': 'assets/icons/adwaita/mimetypes/text-x-markdown.svg',
  'text-x-maxima-out': 'assets/icons/adwaita/mimetypes/text-x-maxima-out.svg',
  'text-x-maximasession': 'assets/icons/adwaita/mimetypes/text-x-maximasession.svg',
  'text-x-meson': 'assets/icons/adwaita/mimetypes/text-x-meson.svg',
  'text-x-ocaml': 'assets/icons/adwaita/mimetypes/text-x-ocaml.svg',
  'text-x-octave': 'assets/icons/adwaita/mimetypes/text-x-octave.svg',
  'text-x-patch': 'assets/icons/adwaita/mimetypes/text-x-patch.svg',
  'text-x-python': 'assets/icons/adwaita/mimetypes/text-x-python.svg',
  'text-x-r-markdown': 'assets/icons/adwaita/mimetypes/text-x-r-markdown.svg',
  'text-x-r': 'assets/icons/adwaita/mimetypes/text-x-r.svg',
  'text-x-ruby': 'assets/icons/adwaita/mimetypes/text-x-ruby.svg',
  'text-x-tex': 'assets/icons/adwaita/mimetypes/text-x-tex.svg',
  'text-x-typescript': 'assets/icons/adwaita/mimetypes/text-x-typescript.svg',
  'text-x-typst': 'assets/icons/adwaita/mimetypes/text-x-typst.svg',
  'text-x-vala': 'assets/icons/adwaita/mimetypes/text-x-vala.svg',
  'text-x-zig': 'assets/icons/adwaita/mimetypes/text-x-zig.svg',
  'video-x-generic': 'assets/icons/adwaita/mimetypes/video-x-generic.svg',
  'virtualbox-hdd': 'assets/icons/adwaita/mimetypes/virtualbox-hdd.svg',
  'virtualbox-ova': 'assets/icons/adwaita/mimetypes/virtualbox-ova.svg',
  'virtualbox-ovf': 'assets/icons/adwaita/mimetypes/virtualbox-ovf.svg',
  'virtualbox-vbox-extpack': 'assets/icons/adwaita/mimetypes/virtualbox-vbox-extpack.svg',
  'virtualbox-vbox': 'assets/icons/adwaita/mimetypes/virtualbox-vbox.svg',
  'virtualbox-vdi': 'assets/icons/adwaita/mimetypes/virtualbox-vdi.svg',
  'virtualbox-vhd': 'assets/icons/adwaita/mimetypes/virtualbox-vhd.svg',
  'virtualbox-vmdk': 'assets/icons/adwaita/mimetypes/virtualbox-vmdk.svg',
  'x-office-document': 'assets/icons/adwaita/mimetypes/x-office-document.svg',
  'folder-3dbenchy': 'assets/icons/adwaita/places/folder-3dbenchy.svg',
  'folder-android': 'assets/icons/adwaita/places/folder-android.svg',
  'folder-appimage': 'assets/icons/adwaita/places/folder-appimage.svg',
  'folder-archlinux': 'assets/icons/adwaita/places/folder-archlinux.svg',
  'folder-arduino': 'assets/icons/adwaita/places/folder-arduino.svg',
  'folder-backup': 'assets/icons/adwaita/places/folder-backup.svg',
  'folder-bitwig': 'assets/icons/adwaita/places/folder-bitwig.svg',
  'folder-blender': 'assets/icons/adwaita/places/folder-blender.svg',
  'folder-books': 'assets/icons/adwaita/places/folder-books.svg',
  'folder-camera': 'assets/icons/adwaita/places/folder-camera.svg',
  'folder-cloud': 'assets/icons/adwaita/places/folder-cloud.svg',
  'folder-codeberg': 'assets/icons/adwaita/places/folder-codeberg.svg',
  'folder-code': 'assets/icons/adwaita/places/folder-code.svg',
  'folder-cplusplus': 'assets/icons/adwaita/places/folder-cplusplus.svg',
  'folder-csharp': 'assets/icons/adwaita/places/folder-csharp.svg',
  'folder-c': 'assets/icons/adwaita/places/folder-c.svg',
  'folder-docker': 'assets/icons/adwaita/places/folder-docker.svg',
  'folder-documents': 'assets/icons/adwaita/places/folder-documents.svg',
  'folder-download': 'assets/icons/adwaita/places/folder-download.svg',
  'folder-drag-accept': 'assets/icons/adwaita/places/folder-drag-accept.svg',
  'folder-dropbox': 'assets/icons/adwaita/places/folder-dropbox.svg',
  'folder-earth': 'assets/icons/adwaita/places/folder-earth.svg',
  'folder-emacs': 'assets/icons/adwaita/places/folder-emacs.svg',
  'folder-extensions': 'assets/icons/adwaita/places/folder-extensions.svg',
  'folder-fedora': 'assets/icons/adwaita/places/folder-fedora.svg',
  'folder-flatpak': 'assets/icons/adwaita/places/folder-flatpak.svg',
  'folder-freecad': 'assets/icons/adwaita/places/folder-freecad.svg',
  'folder-games': 'assets/icons/adwaita/places/folder-games.svg',
  'folder-gimp': 'assets/icons/adwaita/places/folder-gimp.svg',
  'folder-github': 'assets/icons/adwaita/places/folder-github.svg',
  'folder-gitlab': 'assets/icons/adwaita/places/folder-gitlab.svg',
  'folder-git': 'assets/icons/adwaita/places/folder-git.svg',
  'folder-globe': 'assets/icons/adwaita/places/folder-globe.svg',
  'folder-gnome': 'assets/icons/adwaita/places/folder-gnome.svg',
  'folder-godot': 'assets/icons/adwaita/places/folder-godot.svg',
  'folder-google-drive': 'assets/icons/adwaita/places/folder-google-drive.svg',
  'folder-go': 'assets/icons/adwaita/places/folder-go.svg',
  'folder-inkscape': 'assets/icons/adwaita/places/folder-inkscape.svg',
  'folder-java': 'assets/icons/adwaita/places/folder-java.svg',
  'folder-kde': 'assets/icons/adwaita/places/folder-kde.svg',
  'folder-kicad': 'assets/icons/adwaita/places/folder-kicad.svg',
  'folder-local': 'assets/icons/adwaita/places/folder-local.svg',
  'folder-lua': 'assets/icons/adwaita/places/folder-lua.svg',
  'folder-mega': 'assets/icons/adwaita/places/folder-mega.svg',
  'folder-money': 'assets/icons/adwaita/places/folder-money.svg',
  'folder-musescore': 'assets/icons/adwaita/places/folder-musescore.svg',
  'folder-music': 'assets/icons/adwaita/places/folder-music.svg',
  'folder-neovim': 'assets/icons/adwaita/places/folder-neovim.svg',
  'folder-nextcloud': 'assets/icons/adwaita/places/folder-nextcloud.svg',
  'folder-nix': 'assets/icons/adwaita/places/folder-nix.svg',
  'folder-obsidian': 'assets/icons/adwaita/places/folder-obsidian.svg',
  'folder-obs': 'assets/icons/adwaita/places/folder-obs.svg',
  'folder-onedrive': 'assets/icons/adwaita/places/folder-onedrive.svg',
  'folder-openscad': 'assets/icons/adwaita/places/folder-openscad.svg',
  'folder-opensuse': 'assets/icons/adwaita/places/folder-opensuse.svg',
  'folder-pictures': 'assets/icons/adwaita/places/folder-pictures.svg',
  'folder-platformio': 'assets/icons/adwaita/places/folder-platformio.svg',
  'folder-plugdata': 'assets/icons/adwaita/places/folder-plugdata.svg',
  'folder-podcast': 'assets/icons/adwaita/places/folder-podcast.svg',
  'folder-podman': 'assets/icons/adwaita/places/folder-podman.svg',
  'folder-private': 'assets/icons/adwaita/places/folder-private.svg',
  'folder-projects': 'assets/icons/adwaita/places/folder-projects.svg',
  'folder-publicshare': 'assets/icons/adwaita/places/folder-publicshare.svg',
  'folder-python': 'assets/icons/adwaita/places/folder-python.svg',
  'folder-raspberry-pi': 'assets/icons/adwaita/places/folder-raspberry-pi.svg',
  'folder-reaper': 'assets/icons/adwaita/places/folder-reaper.svg',
  'folder-recent': 'assets/icons/adwaita/places/folder-recent.svg',
  'folder-redhat': 'assets/icons/adwaita/places/folder-redhat.svg',
  'folder-remote': 'assets/icons/adwaita/places/folder-remote.svg',
  'folder-r': 'assets/icons/adwaita/places/folder-r.svg',
  'folder-ruby': 'assets/icons/adwaita/places/folder-ruby.svg',
  'folder-rust': 'assets/icons/adwaita/places/folder-rust.svg',
  'folder-school': 'assets/icons/adwaita/places/folder-school.svg',
  'folder-screencast': 'assets/icons/adwaita/places/folder-screencast.svg',
  'folder-screenshot': 'assets/icons/adwaita/places/folder-screenshot.svg',
  'folder-shell': 'assets/icons/adwaita/places/folder-shell.svg',
  'folder-adw': 'assets/icons/adwaita/places/folder.svg',
  'folder-syncthing': 'assets/icons/adwaita/places/folder-syncthing.svg',
  'folder-templates': 'assets/icons/adwaita/places/folder-templates.svg',
  'folder-temp': 'assets/icons/adwaita/places/folder-temp.svg',
  'folder-torrent': 'assets/icons/adwaita/places/folder-torrent.svg',
  'folder-translation': 'assets/icons/adwaita/places/folder-translation.svg',
  'folder-ubuntu': 'assets/icons/adwaita/places/folder-ubuntu.svg',
  'folder-user': 'assets/icons/adwaita/places/folder-user.svg',
  'folder-vala': 'assets/icons/adwaita/places/folder-vala.svg',
  'folder-videos': 'assets/icons/adwaita/places/folder-videos.svg',
  'folder-wine': 'assets/icons/adwaita/places/folder-wine.svg',
  'folder-work': 'assets/icons/adwaita/places/folder-work.svg',
  'go-home': 'assets/icons/adwaita/places/go-home.svg',
};
