import { WorkflowTemplate } from '../../../flow/workflow/types/workflow.types';

export const BUILTIN_WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'tpl-daily-backup-notify',
    name: 'Daily Backup & Notification',
    description:
      'Runs a scheduled daily sync at 02:00, notifying you on success or alert on failure.',
    category: 'backup',
    icon: 'cloud-arrow-up',
    definition: {
      name: 'Daily Backup & Notification',
      description: 'Scheduled daily backup with desktop alerts.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-trigger-cron',
          type: 'cron',
          category: 'trigger',
          title: 'Daily at 02:00',
          subtitle: '0 2 * * *',
          icon: 'clock',
          x: 100,
          y: 200,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'Trigger' }],
          config: {
            cronExpression: '0 2 * * *',
          },
        },
        {
          id: 'node-task-sync',
          type: 'sync',
          category: 'task',
          title: 'Sync to Cloud Backup',
          subtitle: 'Documents -> Backup',
          icon: 'sync',
          x: 400,
          y: 200,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'success', name: 'Success', type: 'success', label: 'On Success' },
            { id: 'failure', name: 'Failure', type: 'failure', label: 'On Failure' },
          ],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: {
                srcFs: '/home/user/Documents',
                dstFs: 'backup/Documents',
              },
            },
          },
        },
        {
          id: 'node-action-notify-success',
          type: 'notification',
          category: 'action',
          title: 'Backup Successful',
          subtitle: 'Daily sync completed',
          icon: 'bell',
          x: 740,
          y: 120,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'Backup Complete',
            message: 'All files were backed up successfully.',
            severity: 'info',
          },
        },
        {
          id: 'node-action-notify-fail',
          type: 'notification',
          category: 'action',
          title: 'Backup Failed',
          subtitle: 'Check error logs',
          icon: 'warning',
          x: 740,
          y: 280,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'Backup Failed',
            message: 'Daily backup encountered an error.',
            severity: 'error',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-trigger-cron',
          sourcePortId: 'out',
          targetNodeId: 'node-task-sync',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-task-sync',
          sourcePortId: 'success',
          targetNodeId: 'node-action-notify-success',
          targetPortId: 'in',
        },
        {
          id: 'edge-3',
          sourceNodeId: 'node-task-sync',
          sourcePortId: 'failure',
          targetNodeId: 'node-action-notify-fail',
          targetPortId: 'in',
        },
      ],
    },
  },
  {
    id: 'tpl-watch-auto-upload',
    name: 'Folder Watcher & Auto Upload',
    description:
      'Monitors a local folder for changes and copies new/modified files to cloud storage.',
    category: 'automation',
    icon: 'sync',
    definition: {
      name: 'Folder Watcher & Auto Upload',
      description: 'Auto-sync files when local folder changes.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-trigger-watcher',
          type: 'watcher',
          category: 'trigger',
          title: 'Folder Watcher',
          subtitle: 'Monitors /Downloads',
          icon: 'sync',
          x: 100,
          y: 200,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'On Change' }],
          config: {
            watchPaths: ['/home/user/Downloads'],
            debounceSeconds: 5,
          },
        },
        {
          id: 'node-task-copy',
          type: 'copy',
          category: 'task',
          title: 'Copy to Cloud',
          subtitle: 'Upload new files',
          icon: 'copy',
          x: 400,
          y: 200,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'success', name: 'Success', type: 'success', label: 'On Success' }],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: {
                srcFs: '/home/user/Downloads',
                dstFs: 'cloud-inbox',
              },
            },
          },
        },
        {
          id: 'node-action-notify',
          type: 'notification',
          category: 'action',
          title: 'Upload Finished',
          subtitle: 'New files uploaded',
          icon: 'bell',
          x: 720,
          y: 200,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [],
          config: {
            title: 'Auto Upload Finished',
            message: 'Detected files uploaded successfully.',
            severity: 'info',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-trigger-watcher',
          sourcePortId: 'out',
          targetNodeId: 'node-task-copy',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-task-copy',
          sourcePortId: 'success',
          targetNodeId: 'node-action-notify',
          targetPortId: 'in',
        },
      ],
    },
  },
  {
    id: 'tpl-parallel-mirror',
    name: 'Multi-Cloud Parallel Mirror',
    description:
      'Syncs data simultaneously to two different cloud providers, then verifies completion.',
    category: 'sync',
    icon: 'flow',
    definition: {
      name: 'Multi-Cloud Parallel Mirror',
      description: 'Parallel synchronization across multiple remotes.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-manual',
          type: 'manual',
          category: 'trigger',
          title: 'Manual Run',
          subtitle: 'Trigger on demand',
          icon: 'play',
          x: 100,
          y: 250,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'Start' }],
          config: {},
        },
        {
          id: 'node-fork',
          type: 'parallel_fork',
          category: 'logic',
          title: 'Parallel Split',
          subtitle: 'Run both branches',
          icon: 'flow',
          x: 360,
          y: 250,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'branch1', name: 'Branch 1', type: 'out', label: 'Branch 1' },
            { id: 'branch2', name: 'Branch 2', type: 'out', label: 'Branch 2' },
          ],
          config: {},
        },
        {
          id: 'node-sync-a',
          type: 'sync',
          category: 'task',
          title: 'Sync to Remote A',
          subtitle: 'Cloud Primary',
          icon: 'sync',
          x: 620,
          y: 150,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'success', name: 'Success', type: 'success', label: 'Done' }],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: { srcFs: '/data', dstFs: 'remote-a:data' },
            },
          },
        },
        {
          id: 'node-sync-b',
          type: 'sync',
          category: 'task',
          title: 'Sync to Remote B',
          subtitle: 'Cloud Secondary',
          icon: 'sync',
          x: 620,
          y: 350,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'success', name: 'Success', type: 'success', label: 'Done' }],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: { srcFs: '/data', dstFs: 'remote-b:data' },
            },
          },
        },
        {
          id: 'node-join',
          type: 'join',
          category: 'logic',
          title: 'Join Branches',
          subtitle: 'Wait for both',
          icon: 'done-all',
          x: 900,
          y: 250,
          inputs: [
            { id: 'in1', name: 'In 1', type: 'in', label: 'From A' },
            { id: 'in2', name: 'In 2', type: 'in', label: 'From B' },
          ],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'All Done' }],
          config: {},
        },
        {
          id: 'node-notify-done',
          type: 'notification',
          category: 'action',
          title: 'Mirroring Complete',
          subtitle: 'Both remotes in sync',
          icon: 'bell',
          x: 1140,
          y: 250,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [],
          config: {
            title: 'Mirror Complete',
            message: 'All parallel cloud sync operations finished.',
            severity: 'success',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-manual',
          sourcePortId: 'out',
          targetNodeId: 'node-fork',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-fork',
          sourcePortId: 'branch1',
          targetNodeId: 'node-sync-a',
          targetPortId: 'in',
        },
        {
          id: 'edge-3',
          sourceNodeId: 'node-fork',
          sourcePortId: 'branch2',
          targetNodeId: 'node-sync-b',
          targetPortId: 'in',
        },
        {
          id: 'edge-4',
          sourceNodeId: 'node-sync-a',
          sourcePortId: 'success',
          targetNodeId: 'node-join',
          targetPortId: 'in1',
        },
        {
          id: 'edge-5',
          sourceNodeId: 'node-sync-b',
          sourcePortId: 'success',
          targetNodeId: 'node-join',
          targetPortId: 'in2',
        },
        {
          id: 'edge-6',
          sourceNodeId: 'node-join',
          sourcePortId: 'out',
          targetNodeId: 'node-notify-done',
          targetPortId: 'in',
        },
      ],
    },
  },
  {
    id: 'tpl-mount-work',
    name: 'Mount on Demand & Notify',
    description: 'Mounts a remote storage path and notifies desktop when drive is ready.',
    category: 'utility',
    icon: 'folder',
    definition: {
      name: 'Mount on Demand',
      description: 'Quick mount workflow with delay and alert.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-manual',
          type: 'manual',
          category: 'trigger',
          title: 'Mount Remote',
          subtitle: 'Start on demand',
          icon: 'play',
          x: 100,
          y: 200,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'Start' }],
          config: {},
        },
        {
          id: 'node-mount',
          type: 'mount',
          category: 'task',
          title: 'Mount Drive',
          subtitle: 'Mount point',
          icon: 'folder',
          x: 380,
          y: 200,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'success', name: 'Success', type: 'success', label: 'Mounted' }],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: {
                fs: '',
                mountPoint: '/mnt/cloud-drive',
              },
            },
          },
        },
        {
          id: 'node-notify',
          type: 'notification',
          category: 'action',
          title: 'Drive Ready',
          subtitle: 'Filesystem mounted',
          icon: 'bell',
          x: 680,
          y: 200,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [],
          config: {
            title: 'Drive Mounted',
            message: 'Your remote storage is mounted and ready to use.',
            severity: 'info',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-manual',
          sourcePortId: 'out',
          targetNodeId: 'node-mount',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-mount',
          sourcePortId: 'success',
          targetNodeId: 'node-notify',
          targetPortId: 'in',
        },
      ],
    },
  },
];
