import { WorkflowTemplate } from '../../../flow/workflow/types/workflow.types';

export const BUILTIN_WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'tpl-drift-check-sync',
    name: 'Smart Drift Check & Conditional Sync',
    nameKey: 'flow.workflow.recipes.driftCheckSync.name',
    description:
      'Verifies differences with check; synchronizes only when drift is detected and notifies with volume details.',
    descriptionKey: 'flow.workflow.recipes.driftCheckSync.description',
    category: 'sync',
    icon: 'shield',
    definition: {
      name: 'Smart Drift Check & Conditional Sync',
      description: 'Audit drift before sync; transfer only if discrepancies exist.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-manual',
          type: 'manual',
          category: 'trigger',
          title: 'Run On Demand',
          subtitle: 'Start verification',
          x: 80,
          y: 220,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'Start' }],
          config: {},
        },
        {
          id: 'node-task-check',
          type: 'check',
          category: 'task',
          title: 'Check Differences',
          subtitle: 'operations/check',
          x: 340,
          y: 220,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'success', name: 'Success', type: 'success', label: 'Checked' },
            { id: 'failure', name: 'Failure', type: 'failure', label: 'On Failure' },
          ],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: {
                srcFs: '/data/source',
                dstFs: 'backup:destination',
              },
            },
          },
        },
        {
          id: 'node-condition',
          type: 'condition',
          category: 'logic',
          title: 'Has Differences?',
          subtitle: 'prev.hasDifferences == true',
          x: 640,
          y: 220,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'true', name: 'True', type: 'true', label: 'Drift Found' },
            { id: 'false', name: 'False', type: 'false', label: 'In Sync' },
          ],
          config: {
            operator: 'equals',
            leftValue: '{{prev.hasDifferences}}',
            rightValue: 'true',
            targetNodeId: 'prev',
            field: 'hasDifferences',
          },
        },
        {
          id: 'node-task-sync',
          type: 'sync',
          category: 'task',
          title: 'Sync Drifted Files',
          subtitle: 'Apply changes',
          x: 940,
          y: 140,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'success', name: 'Success', type: 'success', label: 'On Success' },
            { id: 'failure', name: 'Failure', type: 'failure', label: 'On Failure' },
          ],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: {
                srcFs: '/data/source',
                dstFs: 'backup:destination',
              },
            },
          },
        },
        {
          id: 'node-notify-sync-done',
          type: 'notification',
          category: 'action',
          title: 'Sync Complete',
          subtitle: 'Drift resolved',
          x: 1240,
          y: 140,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'Sync Completed',
            message:
              'Drift resolved: {{prev.bytesFormatted}} transferred ({{prev.transfers}} files).',
            severity: 'info',
          },
        },
        {
          id: 'node-notify-in-sync',
          type: 'notification',
          category: 'action',
          title: 'Already In Sync',
          subtitle: 'No drift found',
          x: 940,
          y: 320,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'No Drift Detected',
            message: 'Source and destination are already identical. Sync was skipped.',
            severity: 'info',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-manual',
          sourcePortId: 'out',
          targetNodeId: 'node-task-check',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-task-check',
          sourcePortId: 'success',
          targetNodeId: 'node-condition',
          targetPortId: 'in',
        },
        {
          id: 'edge-3',
          sourceNodeId: 'node-condition',
          sourcePortId: 'true',
          targetNodeId: 'node-task-sync',
          targetPortId: 'in',
        },
        {
          id: 'edge-4',
          sourceNodeId: 'node-task-sync',
          sourcePortId: 'success',
          targetNodeId: 'node-notify-sync-done',
          targetPortId: 'in',
        },
        {
          id: 'edge-5',
          sourceNodeId: 'node-condition',
          sourcePortId: 'false',
          targetNodeId: 'node-notify-in-sync',
          targetPortId: 'in',
        },
      ],
    },
  },
  {
    id: 'tpl-integrity-audit',
    name: 'Data Integrity Audit & Drift Report',
    nameKey: 'flow.workflow.recipes.integrityAudit.name',
    description:
      'Runs a scheduled integrity check; sends an alert with a formatted Markdown difference report if differences exist.',
    descriptionKey: 'flow.workflow.recipes.integrityAudit.description',
    category: 'utility',
    icon: 'file-lines',
    definition: {
      name: 'Data Integrity Audit & Drift Report',
      description: 'Scheduled hash and size verification with report alert.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-trigger-cron',
          type: 'cron',
          category: 'trigger',
          title: 'Weekly Audit',
          subtitle: '0 3 * * 0',
          x: 80,
          y: 220,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'Trigger' }],
          config: {
            cronExpression: '0 3 * * 0',
          },
        },
        {
          id: 'node-task-check',
          type: 'check',
          category: 'task',
          title: 'Integrity Check',
          subtitle: 'operations/check',
          x: 340,
          y: 220,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'success', name: 'Success', type: 'success', label: 'Done' },
            { id: 'failure', name: 'Failure', type: 'failure', label: 'On Failure' },
          ],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: {
                srcFs: '/data/vault',
                dstFs: 'cloud:backup/vault',
              },
            },
          },
        },
        {
          id: 'node-condition',
          type: 'condition',
          category: 'logic',
          title: 'Differences Found?',
          subtitle: 'prev.hasDifferences == true',
          x: 640,
          y: 220,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'true', name: 'True', type: 'true', label: 'Drift' },
            { id: 'false', name: 'False', type: 'false', label: 'Matching' },
          ],
          config: {
            operator: 'equals',
            leftValue: '{{prev.hasDifferences}}',
            rightValue: 'true',
            targetNodeId: 'prev',
            field: 'hasDifferences',
          },
        },
        {
          id: 'node-notify-drift',
          type: 'notification',
          category: 'action',
          title: 'Drift Alert',
          subtitle: 'Send report',
          x: 940,
          y: 140,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'Integrity Audit Alert',
            message: 'Audit detected {{prev.differCount}} differing file(s)!\n\n{{prev.report}}',
            severity: 'warning',
          },
        },
        {
          id: 'node-notify-clean',
          type: 'notification',
          category: 'action',
          title: 'Integrity Verified',
          subtitle: 'All files match',
          x: 940,
          y: 320,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'Integrity Verified',
            message: 'All files match destination. No discrepancies found.',
            severity: 'info',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-trigger-cron',
          sourcePortId: 'out',
          targetNodeId: 'node-task-check',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-task-check',
          sourcePortId: 'success',
          targetNodeId: 'node-condition',
          targetPortId: 'in',
        },
        {
          id: 'edge-3',
          sourceNodeId: 'node-condition',
          sourcePortId: 'true',
          targetNodeId: 'node-notify-drift',
          targetPortId: 'in',
        },
        {
          id: 'edge-4',
          sourceNodeId: 'node-condition',
          sourcePortId: 'false',
          targetNodeId: 'node-notify-clean',
          targetPortId: 'in',
        },
      ],
    },
  },
  {
    id: 'tpl-safe-sync-alert',
    name: 'Safe Sync with Failure Alert',
    nameKey: 'flow.workflow.recipes.safeSyncAlert.name',
    description:
      'Runs a sync operation, notifying with transfer volume on success or forwarding exact error details on failure.',
    descriptionKey: 'flow.workflow.recipes.safeSyncAlert.description',
    category: 'backup',
    icon: 'bell',
    definition: {
      name: 'Safe Sync with Failure Alert',
      description: 'Sync with error handling and dynamic completion stats.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-manual',
          type: 'manual',
          category: 'trigger',
          title: 'Manual Run',
          subtitle: 'On demand',
          x: 80,
          y: 220,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'Start' }],
          config: {},
        },
        {
          id: 'node-task-sync',
          type: 'sync',
          category: 'task',
          title: 'Sync to Remote',
          subtitle: 'Local -> Remote',
          x: 360,
          y: 220,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'success', name: 'Success', type: 'success', label: 'On Success' },
            { id: 'failure', name: 'Failure', type: 'failure', label: 'On Failure' },
          ],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: {
                srcFs: '/data',
                dstFs: 'backup:data',
              },
            },
          },
        },
        {
          id: 'node-notify-success',
          type: 'notification',
          category: 'action',
          title: 'Sync Succeeded',
          subtitle: 'Transfer summary',
          x: 680,
          y: 140,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'Sync Succeeded',
            message:
              'Transferred: {{prev.bytesFormatted}} (Speed: {{prev.speedFormatted}}). All files up to date.',
            severity: 'success',
          },
        },
        {
          id: 'node-notify-fail',
          type: 'notification',
          category: 'action',
          title: 'Sync Failed',
          subtitle: 'Error alert',
          x: 680,
          y: 300,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'Sync Failed',
            message: 'Backup encountered an error:\n{{prev.error}}',
            severity: 'error',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-manual',
          sourcePortId: 'out',
          targetNodeId: 'node-task-sync',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-task-sync',
          sourcePortId: 'success',
          targetNodeId: 'node-notify-success',
          targetPortId: 'in',
        },
        {
          id: 'edge-3',
          sourceNodeId: 'node-task-sync',
          sourcePortId: 'failure',
          targetNodeId: 'node-notify-fail',
          targetPortId: 'in',
        },
      ],
    },
  },
  {
    id: 'tpl-daily-backup-notify',
    name: 'Daily Backup & Notification',
    nameKey: 'flow.workflow.recipes.dailyBackup.name',
    description:
      'Runs a scheduled daily sync at 02:00, notifying you on success or alert on failure.',
    descriptionKey: 'flow.workflow.recipes.dailyBackup.description',
    category: 'backup',
    icon: 'cloud-arrow-up',
    definition: {
      name: 'Daily Backup & Notification',
      description: 'Scheduled daily backup with desktop alerts.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-trigger-cron',
          type: 'cron',
          category: 'trigger',
          title: 'Daily at 02:00',
          subtitle: '0 2 * * *',
          x: 100,
          y: 200,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'Trigger' }],
          config: {
            cronExpression: '0 2 * * *',
          },
        },
        {
          id: 'node-task-sync',
          type: 'sync',
          category: 'task',
          title: 'Sync to Cloud Backup',
          subtitle: 'Documents -> Backup',
          x: 400,
          y: 200,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'success', name: 'Success', type: 'success', label: 'On Success' },
            { id: 'failure', name: 'Failure', type: 'failure', label: 'On Failure' },
          ],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: {
                srcFs: '/home/user/Documents',
                dstFs: 'backup/Documents',
              },
            },
          },
        },
        {
          id: 'node-action-notify-success',
          type: 'notification',
          category: 'action',
          title: 'Backup Successful',
          subtitle: 'Daily sync completed',
          x: 740,
          y: 120,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'Backup Complete',
            message:
              'Daily sync completed: {{prev.bytesFormatted}} transferred (Speed: {{prev.speedFormatted}}).',
            severity: 'info',
          },
        },
        {
          id: 'node-action-notify-fail',
          type: 'notification',
          category: 'action',
          title: 'Backup Failed',
          subtitle: 'Check error logs',
          x: 740,
          y: 280,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'Backup Failed',
            message: 'Daily backup encountered an error:\n{{prev.error}}',
            severity: 'error',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-trigger-cron',
          sourcePortId: 'out',
          targetNodeId: 'node-task-sync',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-task-sync',
          sourcePortId: 'success',
          targetNodeId: 'node-action-notify-success',
          targetPortId: 'in',
        },
        {
          id: 'edge-3',
          sourceNodeId: 'node-task-sync',
          sourcePortId: 'failure',
          targetNodeId: 'node-action-notify-fail',
          targetPortId: 'in',
        },
      ],
    },
  },
  {
    id: 'tpl-watch-auto-upload',
    name: 'Folder Watcher & Auto Upload',
    nameKey: 'flow.workflow.recipes.watchUpload.name',
    description:
      'Monitors a local folder for changes and copies new/modified files to cloud storage.',
    descriptionKey: 'flow.workflow.recipes.watchUpload.description',
    category: 'automation',
    icon: 'sync',
    definition: {
      name: 'Folder Watcher & Auto Upload',
      description: 'Auto-sync files when local folder changes.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-trigger-watcher',
          type: 'watcher',
          category: 'trigger',
          title: 'Folder Watcher',
          subtitle: 'Monitors /Downloads',
          x: 100,
          y: 200,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'On Change' }],
          config: {
            watchPaths: ['/home/user/Downloads'],
            debounceSeconds: 5,
          },
        },
        {
          id: 'node-task-copy',
          type: 'copy',
          category: 'task',
          title: 'Copy to Cloud',
          subtitle: 'Upload new files',
          x: 400,
          y: 200,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'success', name: 'Success', type: 'success', label: 'On Success' }],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: {
                srcFs: '/home/user/Downloads',
                dstFs: 'cloud-inbox',
              },
            },
          },
        },
        {
          id: 'node-action-notify',
          type: 'notification',
          category: 'action',
          title: 'Upload Finished',
          subtitle: 'New files uploaded',
          x: 720,
          y: 200,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [],
          config: {
            title: 'Auto Upload Finished',
            message:
              'Auto upload completed: {{prev.bytesFormatted}} transferred ({{prev.transfers}} files).',
            severity: 'info',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-trigger-watcher',
          sourcePortId: 'out',
          targetNodeId: 'node-task-copy',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-task-copy',
          sourcePortId: 'success',
          targetNodeId: 'node-action-notify',
          targetPortId: 'in',
        },
      ],
    },
  },
  {
    id: 'tpl-parallel-mirror',
    name: 'Multi-Cloud Parallel Mirror',
    nameKey: 'flow.workflow.recipes.parallelMirror.name',
    description:
      'Syncs data simultaneously to two different cloud providers, then verifies completion.',
    descriptionKey: 'flow.workflow.recipes.parallelMirror.description',
    category: 'sync',
    icon: 'flow',
    definition: {
      name: 'Multi-Cloud Parallel Mirror',
      description: 'Parallel synchronization across multiple remotes.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-manual',
          type: 'manual',
          category: 'trigger',
          title: 'Manual Run',
          subtitle: 'Trigger on demand',
          x: 100,
          y: 250,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'Start' }],
          config: {},
        },
        {
          id: 'node-fork',
          type: 'parallel_fork',
          category: 'logic',
          title: 'Parallel Split',
          subtitle: 'Run both branches',
          x: 360,
          y: 250,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'branch1', name: 'Branch 1', type: 'out', label: 'Branch 1' },
            { id: 'branch2', name: 'Branch 2', type: 'out', label: 'Branch 2' },
          ],
          config: {},
        },
        {
          id: 'node-sync-a',
          type: 'sync',
          category: 'task',
          title: 'Sync to Remote A',
          subtitle: 'Cloud Primary',
          x: 620,
          y: 150,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'success', name: 'Success', type: 'success', label: 'Done' }],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: { srcFs: '/data', dstFs: 'remote-a:data' },
            },
          },
        },
        {
          id: 'node-sync-b',
          type: 'sync',
          category: 'task',
          title: 'Sync to Remote B',
          subtitle: 'Cloud Secondary',
          x: 620,
          y: 350,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'success', name: 'Success', type: 'success', label: 'Done' }],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: { srcFs: '/data', dstFs: 'remote-b:data' },
            },
          },
        },
        {
          id: 'node-join',
          type: 'join',
          category: 'logic',
          title: 'Join Branches',
          subtitle: 'Wait for both',
          x: 900,
          y: 250,
          inputs: [
            { id: 'in1', name: 'In 1', type: 'in', label: 'From A' },
            { id: 'in2', name: 'In 2', type: 'in', label: 'From B' },
          ],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'All Done' }],
          config: {},
        },
        {
          id: 'node-notify-done',
          type: 'notification',
          category: 'action',
          title: 'Mirroring Complete',
          subtitle: 'Both remotes in sync',
          x: 1140,
          y: 250,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [],
          config: {
            title: 'Mirror Complete',
            message: 'All parallel cloud sync operations finished.',
            severity: 'success',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-manual',
          sourcePortId: 'out',
          targetNodeId: 'node-fork',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-fork',
          sourcePortId: 'branch1',
          targetNodeId: 'node-sync-a',
          targetPortId: 'in',
        },
        {
          id: 'edge-3',
          sourceNodeId: 'node-fork',
          sourcePortId: 'branch2',
          targetNodeId: 'node-sync-b',
          targetPortId: 'in',
        },
        {
          id: 'edge-4',
          sourceNodeId: 'node-sync-a',
          sourcePortId: 'success',
          targetNodeId: 'node-join',
          targetPortId: 'in1',
        },
        {
          id: 'edge-5',
          sourceNodeId: 'node-sync-b',
          sourcePortId: 'success',
          targetNodeId: 'node-join',
          targetPortId: 'in2',
        },
        {
          id: 'edge-6',
          sourceNodeId: 'node-join',
          sourcePortId: 'out',
          targetNodeId: 'node-notify-done',
          targetPortId: 'in',
        },
      ],
    },
  },
  {
    id: 'tpl-mount-work',
    name: 'Mount on Demand & Notify',
    nameKey: 'flow.workflow.recipes.mountOnDemand.name',
    description: 'Mounts a remote storage path and notifies desktop when drive is ready.',
    descriptionKey: 'flow.workflow.recipes.mountOnDemand.description',
    category: 'utility',
    icon: 'folder',
    definition: {
      name: 'Mount on Demand',
      description: 'Quick mount workflow with delay and alert.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-manual',
          type: 'manual',
          category: 'trigger',
          title: 'Mount Remote',
          subtitle: 'Start on demand',
          x: 100,
          y: 200,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'Start' }],
          config: {},
        },
        {
          id: 'node-mount',
          type: 'mount',
          category: 'task',
          title: 'Mount Drive',
          subtitle: 'Mount point',
          x: 380,
          y: 200,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'success', name: 'Success', type: 'success', label: 'Mounted' }],
          config: {
            remoteName: '',
            config: {
              app: {
                autoStart: false,
                showOnTray: true,
                cronEnabled: false,
                cronExpression: null,
                watchEnabled: false,
                watchDelay: 5,
                watchChangedOnly: false,
              },
              rclone: {
                fs: '',
                mountPoint: '/mnt/cloud-drive',
              },
            },
          },
        },
        {
          id: 'node-notify',
          type: 'notification',
          category: 'action',
          title: 'Drive Ready',
          subtitle: 'Filesystem mounted',
          x: 680,
          y: 200,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [],
          config: {
            title: 'Drive Mounted',
            message: 'Your remote storage is mounted and ready to use.',
            severity: 'info',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-manual',
          sourcePortId: 'out',
          targetNodeId: 'node-mount',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-mount',
          sourcePortId: 'success',
          targetNodeId: 'node-notify',
          targetPortId: 'in',
        },
      ],
    },
  },
  {
    id: 'tpl-rc-vfs-refresh',
    name: 'VFS Cache Refresh Automation',
    nameKey: 'flow.workflow.recipes.vfsRefresh.name',
    description:
      'Sends a vfs/refresh Remote Control (RC) command to reload directory cache on mounted drives and notifies desktop.',
    descriptionKey: 'flow.workflow.recipes.vfsRefresh.description',
    category: 'automation',
    icon: 'sync',
    definition: {
      name: 'VFS Cache Refresh Automation',
      description: 'Trigger directory cache reload via Rclone RC API.',
      viewport: { x: 50, y: 150, zoom: 1 },
      nodes: [
        {
          id: 'node-manual',
          type: 'manual',
          category: 'trigger',
          title: 'Trigger Refresh',
          subtitle: 'On demand',
          x: 80,
          y: 220,
          inputs: [],
          outputs: [{ id: 'out', name: 'Trigger', type: 'out', label: 'Start' }],
          config: {},
        },
        {
          id: 'node-task-rc',
          type: 'rc_command',
          category: 'task',
          title: 'VFS Cache Refresh',
          subtitle: 'vfs/refresh',
          x: 360,
          y: 220,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [
            { id: 'success', name: 'Success', type: 'success', label: 'Done' },
            { id: 'failure', name: 'Failure', type: 'failure', label: 'On Failure' },
          ],
          config: {
            command: 'vfs/refresh',
            params: { recursive: true },
            sampleOutput: { result: { '': 'OK' } },
          },
        },
        {
          id: 'node-notify-success',
          type: 'notification',
          category: 'action',
          title: 'Cache Refreshed',
          subtitle: 'Drive updated',
          x: 680,
          y: 140,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'VFS Cache Refreshed',
            message:
              'Directory cache reload finished successfully.\nCommand: {{prev.command}}\nStatus: {{prev.status}}',
            severity: 'info',
          },
        },
        {
          id: 'node-notify-fail',
          type: 'notification',
          category: 'action',
          title: 'Refresh Failed',
          subtitle: 'Error alert',
          x: 680,
          y: 300,
          inputs: [{ id: 'in', name: 'In', type: 'in', label: 'In' }],
          outputs: [{ id: 'out', name: 'Out', type: 'out', label: 'Done' }],
          config: {
            title: 'VFS Refresh Failed',
            message: 'RC command failed:\n{{prev.error}}',
            severity: 'error',
          },
        },
      ],
      edges: [
        {
          id: 'edge-1',
          sourceNodeId: 'node-manual',
          sourcePortId: 'out',
          targetNodeId: 'node-task-rc',
          targetPortId: 'in',
        },
        {
          id: 'edge-2',
          sourceNodeId: 'node-task-rc',
          sourcePortId: 'success',
          targetNodeId: 'node-notify-success',
          targetPortId: 'in',
        },
        {
          id: 'edge-3',
          sourceNodeId: 'node-task-rc',
          sourcePortId: 'failure',
          targetNodeId: 'node-notify-fail',
          targetPortId: 'in',
        },
      ],
    },
  },
];
