import { RcConfigExample } from '@app/types';

export const TYPE_DEFAULT_EXAMPLES: Readonly<Record<string, readonly RcConfigExample[]>> = {
  Duration: [
    { Value: '0s', Help: 'rcloneExamples.types.duration.0s' },
    { Value: '10s', Help: 'rcloneExamples.types.duration.10s' },
    { Value: '30s', Help: 'rcloneExamples.types.duration.30s' },
    { Value: '1m', Help: 'rcloneExamples.types.duration.1m' },
    { Value: '5m', Help: 'rcloneExamples.types.duration.5m' },
    { Value: '10m', Help: 'rcloneExamples.types.duration.10m' },
    { Value: '30m', Help: 'rcloneExamples.types.duration.30m' },
    { Value: '1h', Help: 'rcloneExamples.types.duration.1h' },
    { Value: '24h', Help: 'rcloneExamples.types.duration.24h' },
    { Value: '7d', Help: 'rcloneExamples.types.duration.7d' },
    { Value: '30d', Help: 'rcloneExamples.types.duration.30d' },
    { Value: 'off', Help: 'rcloneExamples.types.duration.off' },
  ],
  SizeSuffix: [
    { Value: '0', Help: 'rcloneExamples.types.sizeSuffix.0' },
    { Value: '512k', Help: 'rcloneExamples.types.sizeSuffix.512k' },
    { Value: '1M', Help: 'rcloneExamples.types.sizeSuffix.1M' },
    { Value: '8M', Help: 'rcloneExamples.types.sizeSuffix.8M' },
    { Value: '16M', Help: 'rcloneExamples.types.sizeSuffix.16M' },
    { Value: '32M', Help: 'rcloneExamples.types.sizeSuffix.32M' },
    { Value: '64M', Help: 'rcloneExamples.types.sizeSuffix.64M' },
    { Value: '128M', Help: 'rcloneExamples.types.sizeSuffix.128M' },
    { Value: '256M', Help: 'rcloneExamples.types.sizeSuffix.256M' },
    { Value: '512M', Help: 'rcloneExamples.types.sizeSuffix.512M' },
    { Value: '1G', Help: 'rcloneExamples.types.sizeSuffix.1G' },
    { Value: '10G', Help: 'rcloneExamples.types.sizeSuffix.10G' },
    { Value: '100G', Help: 'rcloneExamples.types.sizeSuffix.100G' },
    { Value: '1T', Help: 'rcloneExamples.types.sizeSuffix.1T' },
    { Value: 'off', Help: 'rcloneExamples.types.sizeSuffix.off' },
  ],
  CountSuffix: [
    { Value: '0', Help: 'rcloneExamples.types.countSuffix.0' },
    { Value: '100', Help: 'rcloneExamples.types.countSuffix.100' },
    { Value: '1k', Help: 'rcloneExamples.types.countSuffix.1k' },
    { Value: '10k', Help: 'rcloneExamples.types.countSuffix.10k' },
    { Value: '100k', Help: 'rcloneExamples.types.countSuffix.100k' },
    { Value: '1M', Help: 'rcloneExamples.types.countSuffix.1M' },
    { Value: '10M', Help: 'rcloneExamples.types.countSuffix.10M' },
    { Value: 'off', Help: 'rcloneExamples.types.countSuffix.off' },
  ],
  BwTimetable: [
    { Value: 'off', Help: 'rcloneExamples.types.bwTimetable.off' },
    { Value: '512k', Help: 'rcloneExamples.types.bwTimetable.512k' },
    { Value: '1M', Help: 'rcloneExamples.types.bwTimetable.1M' },
    { Value: '5M', Help: 'rcloneExamples.types.bwTimetable.5M' },
    { Value: '10M', Help: 'rcloneExamples.types.bwTimetable.10M' },
    { Value: '50M', Help: 'rcloneExamples.types.bwTimetable.50M' },
    { Value: '10M:50M', Help: 'rcloneExamples.types.bwTimetable.split' },
    { Value: '08:00,512k 18:00,10M 23:00,off', Help: 'rcloneExamples.types.bwTimetable.schedule' },
  ],
  FileMode: [
    { Value: '0644', Help: 'rcloneExamples.types.fileMode.0644' },
    { Value: '0666', Help: 'rcloneExamples.types.fileMode.0666' },
    { Value: '0755', Help: 'rcloneExamples.types.fileMode.0755' },
    { Value: '0777', Help: 'rcloneExamples.types.fileMode.0777' },
  ],
  Tristate: [
    { Value: 'true', Help: 'rcloneExamples.types.tristate.true' },
    { Value: 'false', Help: 'rcloneExamples.types.tristate.false' },
    { Value: 'unset', Help: 'rcloneExamples.types.tristate.unset' },
  ],
};
