import { RcConfigOption } from '@app/types';

export const staticFlagDefinitions: Record<string, RcConfigOption[]> = {
  move: [
    {
      Name: 'create-empty-src-dirs',
      Help: 'Create empty source directories on destination after move.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'createEmptySrcDirs',
    },
    {
      Name: 'delete-empty-src-dirs',
      Help: 'Delete empty source directories after move.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'deleteEmptySrcDirs',
    },
  ],
  copy: [
    {
      Name: 'create-empty-src-dirs',
      Help: 'Create empty source directories on destination after copy.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'createEmptySrcDirs',
    },
  ],
  sync: [
    {
      Name: 'create-empty-src-dirs',
      Help: 'Create empty source directories on destination after sync.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'createEmptySrcDirs',
    },
  ],
  bisync: [
    {
      Name: 'dryRun',
      Help: 'Perform a dry-run.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'dryRun',
    },
    {
      Name: 'resync',
      Help: 'Performs the resync run.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'resync',
    },
    {
      Name: 'checkAccess',
      Help: 'Abort if RCLONE_TEST files are not found on both filesystems.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'checkAccess',
    },
    {
      Name: 'checkFilename',
      Help: 'File name for --check-access.',
      Default: 'RCLONE_TEST',
      DefaultStr: 'RCLONE_TEST',
      Value: 'RCLONE_TEST',
      Type: 'string',
      Advanced: false,
      FieldName: 'checkFilename',
    },
    {
      Name: 'maxDelete',
      Help: 'Abort sync if percentage of deleted files is above this threshold.',
      Default: 50,
      DefaultStr: '50',
      Value: 50,
      Type: 'int',
      Advanced: false,
      FieldName: 'maxDelete',
    },
    {
      Name: 'force',
      Help: 'Bypass --max-delete safety check and run the sync.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'force',
    },
    {
      Name: 'checkSync',
      Help: 'Controls comparison of final listings.',
      Default: 'true',
      DefaultStr: 'true',
      Value: 'true',
      Type: 'string',
      Advanced: false,
      FieldName: 'checkSync',
    },
    {
      Name: 'create-empty-src-dirs',
      Help: 'Sync creation and deletion of empty directories.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'createEmptySrcDirs',
    },
    {
      Name: 'remove-empty-dirs',
      Help: 'Remove empty directories at the final cleanup step.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'removeEmptyDirs',
    },
    {
      Name: 'filters-file',
      Help: 'Read filtering patterns from a file.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'filtersFile',
    },
    {
      Name: 'ignore-listing-checksum',
      Help: 'Do not use checksums for listings.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'ignoreListingChecksum',
    },
    {
      Name: 'resilient',
      Help: 'Allow future runs to retry after certain less-serious errors.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'resilient',
    },
    {
      Name: 'work-dir',
      Help: 'Server directory for history files.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'workDir',
    },
    {
      Name: 'backup-dir1',
      Help: '--backup-dir for Path1.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'backupDir1',
    },
    {
      Name: 'backup-dir2',
      Help: '--backup-dir for Path2.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'backupDir2',
    },
    {
      Name: 'no-cleanup',
      Help: 'Retain working files.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'noCleanup',
    },
  ],
};
