import { RcConfigOption } from '@app/types';

export const SUPPORTED_ARCHIVE_FORMATS = [
  'zip',
  'tar',
  'tar.gz',
  'tar.bz2',
  'tar.xz',
  'tar.zst',
  'tar.br',
  'tar.sz',
  'tar.mz',
  'tar.lz',
  'tar.lz4',
] as const;

export const staticFlagDefinitions: Record<string, RcConfigOption[]> = {
  move: [
    {
      Name: 'create-empty-src-dirs',
      Help: 'Create empty source directories on destination after move.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'createEmptySrcDirs',
    },
    {
      Name: 'delete-empty-src-dirs',
      Help: 'Delete empty source directories after move.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'deleteEmptySrcDirs',
    },
  ],
  copy: [
    {
      Name: 'create-empty-src-dirs',
      Help: 'Create empty source directories on destination after copy.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'createEmptySrcDirs',
    },
  ],
  sync: [
    {
      Name: 'create-empty-src-dirs',
      Help: 'Create empty source directories on destination after sync.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'createEmptySrcDirs',
    },
  ],
  check: [
    {
      Name: 'one-way',
      Help: "Do check one way only - find files on source which don't exist on destination.",
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'oneWay',
    },
    {
      Name: 'download',
      Help: 'Check by downloading rather than with hash.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'download',
    },
    {
      Name: 'check-file-hash',
      Help: 'Treat checkFileFs:checkFileRemote as a SUM file with hashes of given type.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'checkFileHash',
    },
    {
      Name: 'check-file-fs',
      Help: 'Treat checkFileFs:checkFileRemote as a SUM file with hashes.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'checkFileFs',
    },
    {
      Name: 'check-file-remote',
      Help: 'Treat checkFileFs:checkFileRemote as a SUM file with hashes.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'checkFileRemote',
    },
    {
      Name: 'combined',
      Help: 'Make a combined report of changes.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'combined',
    },
    {
      Name: 'missing-on-src',
      Help: 'Report all files missing from the source.',
      Default: true,
      DefaultStr: 'true',
      Value: true,
      Type: 'bool',
      Advanced: false,
      FieldName: 'missingOnSrc',
    },
    {
      Name: 'missing-on-dst',
      Help: 'Report all files missing from the destination.',
      Default: true,
      DefaultStr: 'true',
      Value: true,
      Type: 'bool',
      Advanced: false,
      FieldName: 'missingOnDst',
    },
    {
      Name: 'match',
      Help: 'Report all matching files.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'match',
    },
    {
      Name: 'differ',
      Help: 'Report all non-matching files.',
      Default: true,
      DefaultStr: 'true',
      Value: true,
      Type: 'bool',
      Advanced: false,
      FieldName: 'differ',
    },
    {
      Name: 'error',
      Help: 'Report all files with errors (hashing or reading).',
      Default: true,
      DefaultStr: 'true',
      Value: true,
      Type: 'bool',
      Advanced: false,
      FieldName: 'error',
    },
  ],
  bisync: [
    {
      Name: 'dryRun',
      Help: 'Perform a dry-run.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'dryRun',
    },
    {
      Name: 'resync',
      Help: 'Performs the resync run.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'resync',
    },
    {
      Name: 'checkAccess',
      Help: 'Abort if RCLONE_TEST files are not found on both filesystems.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'checkAccess',
    },
    {
      Name: 'checkFilename',
      Help: 'File name for --check-access.',
      Default: 'RCLONE_TEST',
      DefaultStr: 'RCLONE_TEST',
      Value: 'RCLONE_TEST',
      Type: 'string',
      Advanced: false,
      FieldName: 'checkFilename',
    },
    {
      Name: 'maxDelete',
      Help: 'Abort sync if percentage of deleted files is above this threshold.',
      Default: 50,
      DefaultStr: '50',
      Value: 50,
      Type: 'int',
      Advanced: false,
      FieldName: 'maxDelete',
    },
    {
      Name: 'force',
      Help: 'Bypass --max-delete safety check and run the sync.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'force',
    },
    {
      Name: 'checkSync',
      Help: 'Controls comparison of final listings.',
      Default: 'true',
      DefaultStr: 'true',
      Value: 'true',
      Type: 'string',
      Advanced: false,
      FieldName: 'checkSync',
    },
    {
      Name: 'create-empty-src-dirs',
      Help: 'Sync creation and deletion of empty directories.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'createEmptySrcDirs',
    },
    {
      Name: 'remove-empty-dirs',
      Help: 'Remove empty directories at the final cleanup step.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'removeEmptyDirs',
    },
    {
      Name: 'filters-file',
      Help: 'Read filtering patterns from a file.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'filtersFile',
    },
    {
      Name: 'ignore-listing-checksum',
      Help: 'Do not use checksums for listings.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'ignoreListingChecksum',
    },
    {
      Name: 'resilient',
      Help: 'Allow future runs to retry after certain less-serious errors.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'resilient',
    },
    {
      Name: 'work-dir',
      Help: 'Server directory for history files.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'workDir',
    },
    {
      Name: 'backup-dir1',
      Help: '--backup-dir for Path1.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'backupDir1',
    },
    {
      Name: 'backup-dir2',
      Help: '--backup-dir for Path2.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'backupDir2',
    },
    {
      Name: 'no-cleanup',
      Help: 'Retain working files.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'noCleanup',
    },
  ],
  mount: [
    {
      Name: 'mountType',
      FieldName: 'mountType',
      Help: 'Mount type to use.',
      Default: 'mount',
      DefaultStr: 'mount',
      Value: 'mount',
      Type: 'string',
      Advanced: false,
    },
  ],
  serve: [
    {
      Name: 'type',
      FieldName: 'type',
      Help: 'Serve type to use.',
      Default: 'http',
      DefaultStr: 'http',
      Value: 'http',
      Type: 'string',
      Advanced: false,
    },
  ],
  archivecreate: [
    {
      Name: 'format',
      Help: 'Archive format (zip, tar, tgz, tbz, txz, etc.)',
      Default: 'zip',
      DefaultStr: 'zip',
      Value: 'zip',
      Type: 'string',
      Advanced: false,
      FieldName: 'format',
      Examples: SUPPORTED_ARCHIVE_FORMATS.map(fmt => ({
        Value: fmt,
        Help: fmt.toUpperCase() + ' archive',
      })),
    },
    {
      Name: 'prefix',
      Help: 'Add prefix directory in the archive',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'prefix',
    },
    {
      Name: 'full-path',
      Help: 'Use full path of files in the archive',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'fullPath',
    },
  ],
  cryptcheck: [
    {
      Name: 'one-way',
      Help: "Do check one way only - find files on source which don't exist on destination.",
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'oneWay',
    },
    {
      Name: 'download',
      Help: 'Download and decrypt both sides to compare hashes.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'download',
    },
    {
      Name: 'combined',
      Help: 'Make a combined report of changes to this file.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'combined',
    },
    {
      Name: 'differ',
      Help: 'Report all non-matching files to this file.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'differ',
    },
    {
      Name: 'error',
      Help: 'Report all files with errors (hashing or reading) to this file.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'error',
    },
    {
      Name: 'match',
      Help: 'Report all matching files to this file.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'match',
    },
    {
      Name: 'missing-on-dst',
      Help: 'Report all files missing from the destination to this file.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'missingOnDst',
    },
    {
      Name: 'missing-on-src',
      Help: 'Report all files missing from the source to this file.',
      Default: '',
      DefaultStr: '',
      Value: '',
      Type: 'string',
      Advanced: false,
      FieldName: 'missingOnSrc',
    },
  ],
  copyurl: [
    {
      Name: 'auto-filename',
      Help: 'Get the filename from the URL or headers if destination is a directory.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'autoFilename',
    },
  ],
  delete: [
    {
      Name: 'rmdirs',
      Help: 'Remove empty directories after deleting files.',
      Default: false,
      DefaultStr: 'false',
      Value: false,
      Type: 'bool',
      Advanced: false,
      FieldName: 'rmdirs',
    },
  ],
};
