export interface OperationDefinition {
  /** The operation key (e.g., 'sync', 'check', 'mount') */
  readonly key: string;

  // ── Classification flags ──────────────────────────────────
  /** Is this a sync-family operation? (sync, copy, move, bisync, check, etc.) */
  readonly isSyncType: boolean;
  /** Can it be used as a PrimaryAction on the dashboard? Always true for sync types + mount + serve */
  readonly isPrimary: boolean;
  /** Can it appear in the file browser? */
  readonly isBrowsable: boolean;
  /** Can it be a RemoteAction dispatched via tray/card? */
  readonly isRemoteAction: boolean;
  /** Does it support automation (cron/watch)? */
  readonly isAutomatable: boolean;
  /** Does it have its own job type? (some operations share job types) */
  readonly isJobType: boolean;
  /** Does it have linked profiles (own config section)? */
  readonly hasLinkedProfiles: boolean;
  /** Is it a flag type with dedicated flag definitions? */
  readonly isFlagType: boolean;

  // ── Visual metadata ───────────────────────────────────────
  readonly icon: string;
  /** Capitalized label for rclone API calls */
  readonly apiLabel: string;
  /** CSS class for theming */
  readonly cssClass: string;
  /** Animation class when active */
  readonly animationClass: string;

  // ── i18n keys ─────────────────────────────────────────────
  /** e.g., 'actions.check' */
  readonly actionLabel: string;
  /** Active tooltip i18n key */
  readonly activeTooltip: string;
  /** Inactive tooltip i18n key */
  readonly inactiveTooltip: string;

  // ── Dashboard / card metadata ─────────────────────────────
  readonly startIcon: string;
  readonly stopIcon: string;
  readonly startTooltip: string;
  readonly stopTooltip: string;

  // ── Settings panel metadata ───────────────────────────────
  readonly settingsLabel?: string;
  readonly settingsDescription?: string;
  readonly typeLabel?: string;
  readonly supportsVfs?: boolean;
  readonly supportsProfiles?: boolean;

  // ── Config key ────────────────────────────────────────────
  /** Key in RemoteConfigSections, e.g., 'checkConfigs' */
  readonly configKey?: string;
}

// Note: `satisfies readonly OperationDefinition[]` is used so that the keys
// are inferred as exact string literals, allowing union type extraction in other files.
export const OPERATION_REGISTRY = [
  {
    key: 'mount',
    isSyncType: false,
    isPrimary: true,
    isBrowsable: true,
    isRemoteAction: true,
    isAutomatable: false,
    isJobType: false,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'mount',
    apiLabel: 'Mount',
    cssClass: 'accent',
    animationClass: 'animate-breathing',
    actionLabel: 'actions.mount',
    activeTooltip: 'mount.mounted',
    inactiveTooltip: 'mount.toggleAction',
    startIcon: 'mount',
    stopIcon: 'eject',
    startTooltip: 'overviews.remoteCard.actions.mount',
    stopTooltip: 'overviews.remoteCard.actions.unmount',
    settingsLabel: 'dashboard.appDetail.mountSettings',
    settingsDescription: 'dashboard.appDetail.mountBehave',
    typeLabel: 'dashboard.appDetail.mount',
    supportsVfs: true,
    supportsProfiles: true,
    configKey: 'mountConfigs',
  },
  {
    key: 'sync',
    isSyncType: true,
    isPrimary: true,
    isBrowsable: true,
    isRemoteAction: true,
    isAutomatable: true,
    isJobType: true,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'refresh',
    apiLabel: 'Sync',
    cssClass: 'primary',
    animationClass: 'animate-spin',
    actionLabel: 'actions.sync',
    activeTooltip: 'operations.syncing',
    inactiveTooltip: 'operations.toggleSync',
    startIcon: 'refresh',
    stopIcon: 'stop',
    startTooltip: 'overviews.remoteCard.actions.startSync',
    stopTooltip: 'overviews.remoteCard.actions.stopSync',
    settingsLabel: 'dashboard.appDetail.syncSettings',
    settingsDescription: 'dashboard.appDetail.syncDesc',
    typeLabel: 'dashboard.appDetail.sync',
    supportsVfs: false,
    supportsProfiles: true,
    configKey: 'syncConfigs',
  },
  {
    key: 'copy',
    isSyncType: true,
    isPrimary: true,
    isBrowsable: true,
    isRemoteAction: true,
    isAutomatable: true,
    isJobType: true,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'copy',
    apiLabel: 'Copy',
    cssClass: 'yellow',
    animationClass: 'animate-copy',
    actionLabel: 'actions.copy',
    activeTooltip: 'operations.copying',
    inactiveTooltip: 'operations.toggleCopy',
    startIcon: 'copy',
    stopIcon: 'stop',
    startTooltip: 'overviews.remoteCard.actions.startCopy',
    stopTooltip: 'overviews.remoteCard.actions.stopCopy',
    settingsLabel: 'dashboard.appDetail.copySettings',
    settingsDescription: 'dashboard.appDetail.copyDesc',
    typeLabel: 'dashboard.appDetail.copy',
    supportsVfs: false,
    supportsProfiles: true,
    configKey: 'copyConfigs',
  },
  {
    key: 'move',
    isSyncType: true,
    isPrimary: true,
    isBrowsable: true,
    isRemoteAction: true,
    isAutomatable: true,
    isJobType: true,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'move',
    apiLabel: 'Move',
    cssClass: 'orange',
    animationClass: 'animate-move',
    actionLabel: 'actions.move',
    activeTooltip: 'operations.moving',
    inactiveTooltip: 'operations.toggleMove',
    startIcon: 'move',
    stopIcon: 'stop',
    startTooltip: 'overviews.remoteCard.actions.startMove',
    stopTooltip: 'overviews.remoteCard.actions.stopMove',
    settingsLabel: 'dashboard.appDetail.moveSettings',
    settingsDescription: 'dashboard.appDetail.moveDesc',
    typeLabel: 'dashboard.appDetail.move',
    supportsVfs: false,
    supportsProfiles: true,
    configKey: 'moveConfigs',
  },
  {
    key: 'bisync',
    isSyncType: true,
    isPrimary: true,
    isBrowsable: true,
    isRemoteAction: true,
    isAutomatable: true,
    isJobType: true,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'right-left',
    apiLabel: 'Bisync',
    cssClass: 'purple',
    animationClass: 'animate-breathing',
    actionLabel: 'actions.bisync',
    activeTooltip: 'operations.bisyncActive',
    inactiveTooltip: 'operations.toggleBisync',
    startIcon: 'right-left',
    stopIcon: 'stop',
    startTooltip: 'overviews.remoteCard.actions.startBisync',
    stopTooltip: 'overviews.remoteCard.actions.stopBisync',
    settingsLabel: 'dashboard.appDetail.bisyncSettings',
    settingsDescription: 'dashboard.appDetail.bisyncDesc',
    typeLabel: 'dashboard.appDetail.bisync',
    supportsVfs: false,
    supportsProfiles: true,
    configKey: 'bisyncConfigs',
  },
  {
    key: 'serve',
    isSyncType: false,
    isPrimary: true,
    isBrowsable: false,
    isRemoteAction: true,
    isAutomatable: false,
    isJobType: true,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'serve',
    apiLabel: 'Serve',
    cssClass: 'accent',
    animationClass: 'animate-pulse-blue',
    actionLabel: 'actions.serve',
    activeTooltip: 'serve.serving',
    inactiveTooltip: 'serve.toggleAction',
    startIcon: 'satellite-dish',
    stopIcon: 'stop',
    startTooltip: 'overviews.remoteCard.actions.startServe',
    stopTooltip: 'overviews.remoteCard.actions.stopServe',
    settingsLabel: 'dashboard.appDetail.serveSettings',
    settingsDescription: 'dashboard.appDetail.serveBehave',
    typeLabel: 'dashboard.appDetail.serving',
    supportsVfs: true,
    supportsProfiles: true,
    configKey: 'serveConfigs',
  },
  {
    key: 'check',
    isSyncType: true,
    isPrimary: true,
    isBrowsable: true,
    isRemoteAction: false,
    isAutomatable: true,
    isJobType: true,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'search',
    apiLabel: 'Check',
    cssClass: 'accent',
    animationClass: 'animate-breathing',
    actionLabel: 'actions.check',
    activeTooltip: 'operations.checkActive',
    inactiveTooltip: 'operations.toggleCheck',
    startIcon: 'search',
    stopIcon: 'stop',
    startTooltip: 'overviews.remoteCard.actions.startCheck',
    stopTooltip: 'overviews.remoteCard.actions.stopCheck',
    settingsLabel: 'dashboard.appDetail.checkSettings',
    settingsDescription: 'dashboard.appDetail.checkDesc',
    typeLabel: 'dashboard.appDetail.check',
    supportsVfs: false,
    supportsProfiles: true,
    configKey: 'checkConfigs',
  },
  {
    key: 'delete',
    isSyncType: true,
    isPrimary: true,
    isBrowsable: false,
    isRemoteAction: true,
    isAutomatable: true,
    isJobType: true,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'trash',
    apiLabel: 'Delete',
    cssClass: 'warn',
    animationClass: 'animate-breathing',
    actionLabel: 'actions.delete',
    activeTooltip: 'operations.deleteActive',
    inactiveTooltip: 'operations.toggleDelete',
    startIcon: 'trash',
    stopIcon: 'stop',
    startTooltip: 'overviews.remoteCard.actions.startDelete',
    stopTooltip: 'overviews.remoteCard.actions.stopDelete',
    settingsLabel: 'dashboard.appDetail.deleteSettings',
    settingsDescription: 'dashboard.appDetail.deleteDesc',
    typeLabel: 'dashboard.appDetail.delete',
    supportsVfs: false,
    supportsProfiles: true,
    configKey: 'deleteConfigs',
  },
  {
    key: 'copyurl',
    isSyncType: true,
    isPrimary: true,
    isBrowsable: false,
    isRemoteAction: false,
    isAutomatable: true,
    isJobType: true,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'link',
    apiLabel: 'Copyurl',
    cssClass: 'accent',
    animationClass: 'animate-breathing',
    actionLabel: 'actions.copyurl',
    activeTooltip: 'operations.copyurlActive',
    inactiveTooltip: 'operations.toggleCopyurl',
    startIcon: 'link',
    stopIcon: 'stop',
    startTooltip: 'overviews.remoteCard.actions.startCopyurl',
    stopTooltip: 'overviews.remoteCard.actions.stopCopyurl',
    settingsLabel: 'dashboard.appDetail.copyUrlSettings',
    settingsDescription: 'dashboard.appDetail.copyUrlDesc',
    typeLabel: 'dashboard.appDetail.copyurl',
    supportsVfs: false,
    supportsProfiles: true,
    configKey: 'copyurlConfigs',
  },
  {
    key: 'archivecreate',
    isSyncType: true,
    isPrimary: true,
    isBrowsable: false,
    isRemoteAction: false,
    isAutomatable: true,
    isJobType: true,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'compress',
    apiLabel: 'Archivecreate',
    cssClass: 'primary',
    animationClass: 'animate-breathing',
    actionLabel: 'actions.archivecreate',
    activeTooltip: 'operations.archivecreating',
    inactiveTooltip: 'operations.toggleArchivecreate',
    startIcon: 'compress',
    stopIcon: 'stop',
    startTooltip: 'overviews.remoteCard.actions.startArchivecreate',
    stopTooltip: 'overviews.remoteCard.actions.stopArchivecreate',
    settingsLabel: 'dashboard.appDetail.archivecreateSettings',
    settingsDescription: 'dashboard.appDetail.archivecreateDesc',
    typeLabel: 'dashboard.appDetail.archivecreate',
    supportsVfs: false,
    supportsProfiles: true,
    configKey: 'archivecreateConfigs',
  },
  {
    key: 'cryptcheck',
    isSyncType: true,
    isPrimary: true,
    isBrowsable: true,
    isRemoteAction: true,
    isAutomatable: true,
    isJobType: true,
    hasLinkedProfiles: true,
    isFlagType: true,
    icon: 'shield',
    apiLabel: 'Cryptcheck',
    cssClass: 'accent',
    animationClass: 'animate-breathing',
    actionLabel: 'actions.cryptcheck',
    activeTooltip: 'operations.cryptcheckActive',
    inactiveTooltip: 'operations.toggleCryptcheck',
    startIcon: 'shield',
    stopIcon: 'stop',
    startTooltip: 'overviews.remoteCard.actions.startCryptcheck',
    stopTooltip: 'overviews.remoteCard.actions.stopCryptcheck',
    settingsLabel: 'dashboard.appDetail.cryptcheckSettings',
    settingsDescription: 'dashboard.appDetail.cryptcheckDesc',
    typeLabel: 'dashboard.appDetail.cryptcheck',
    supportsVfs: false,
    supportsProfiles: true,
    configKey: 'cryptcheckConfigs',
  },
] as const satisfies readonly OperationDefinition[];
